# Generated by Django 2.0.4 on 2018-04-24 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ailments',
            fields=[
                ('ailmentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ailmentDesc', models.CharField(max_length=100)),
                ('additionalInfo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctorFirstname', models.CharField(max_length=50)),
                ('doctorLastname', models.CharField(max_length=50)),
                ('doctorPhone', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospitalID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalAddress', models.CharField(max_length=400)),
                ('hospitalPhone', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OTCMedicine',
            fields=[
                ('medicineID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicineName', models.CharField(max_length=100)),
                ('medicineUse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientFirstname', models.CharField(max_length=50)),
                ('patientLastname', models.CharField(max_length=50)),
                ('patientAddress', models.CharField(max_length=200)),
                ('patientPhone', models.IntegerField(max_length=15)),
                ('patientAlternateName', models.CharField(blank=True, max_length=200, null=True)),
                ('patientAlternateContact', models.CharField(blank=True, max_length=15, null=True)),
                ('patientViewCode', models.CharField(default='85812', max_length=5)),
            ],
            options={
                'ordering': ('patientLastname', 'patientFirstname'),
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatmentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatmentDescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctorHospital',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='MatrixOfYouApp.Hospital'),
        ),
    ]
