# Generated by Django 2.0.4 on 2018-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrixOfYouApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospitalPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientViewCode',
            field=models.CharField(default='66573', max_length=5),
        ),
    ]
