# Generated by Django 2.0.4 on 2018-04-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrixOfYouApp', '0005_auto_20180424_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientViewCode',
            field=models.CharField(default='89806', max_length=5),
        ),
    ]
