# Generated by Django 2.0.4 on 2018-04-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrixOfYouApp', '0006_auto_20180424_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='MatrixOfYouApp.Treatment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientViewCode',
            field=models.CharField(default='27453', max_length=5),
        ),
    ]
