from .ailments import Ailments
from .doctor import Doctor
from .hospital import Hospital
from .otcMedication import OTCMedicine
from .patient import Patient
from .treatment import Treatment
from .relations.appointments import Appointment
from .relations.otcTaken import OTCMeds
from .relations.patientAilments import patientIllness